#!/bin/sh

function urlenc
{
	/usr/bin/python -c "import sys, urllib as ul; print ul.quote(sys.argv[1],'/')" "$1"
}

FILE=$1
LINE=$2

if [[ $FILE == *.html ]]; then
	open "$FILE"
	exit 1
fi

MVIMVERSION=`/usr/local/bin/mvim --version | grep 'VIM - Vi IMproved' | cut -d ' ' -f 5`
# not 100% accurate, we could have several patch defs e.g. 1-200, 205-300, 302-500
MVIMPATCH=`/usr/local/bin/mvim --version | grep 'Included patches' | cut -d '-' -f 2`

ENC_FILE=`urlenc "$FILE"`

# pre 8.2.319
#   re-encode, since MacVim mistakenly decodes it
# see https://github.com/macvim-dev/macvim/pull/1002
if [[ $MVIMVERSION < '8.2' || $MVIMVERSION == '8.2' && $MVIMPATCH < '319' ]]; then
	ENC_FILE=`urlenc "$ENC_FILE"`
fi

URI="mvim://open?url=file://$ENC_FILE&line=$LINE"

#osascript -e "display notification \"$URI\" with title \"mvimhelper debug\""

open $URI

# going the 'open' way doesn't work as MacVim
# requires args to be set before the file
#open -a /Applications/MacVim.app "$FILE" --args --servername UNITY +$LINE
