#!/bin/sh

function urlenc
{
	/usr/bin/python -c "import sys, urllib as ul; print ul.quote(sys.argv[1],'/')" "$1"
}

FILE=$1
LINE=$2

ENC_FILE=`urlenc "$FILE"`
# re-encode, since MacVim mistakenly decodes it
# https://github.com/macvim-dev/macvim/pull/1002
ENC_FILE=`urlenc "$ENC_FILE"`

URI="mvim://open?url=file://$ENC_FILE&line=$LINE"

#osascript -e "display notification \"$URI\" with title \"mvimhelper debug\""

open $URI

# going the 'open' way doesn't work as MacVim
# requires args to be set before the file
#open -a /Applications/MacVim.app "$FILE" --args --servername UNITY +$LINE
